// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebsiteMonitor.Storage.Data;

#nullable disable

namespace WebsiteMonitor.Storage.Migrations
{
    [DbContext(typeof(WebsiteMonitorDbContext))]
    [Migration("20251228191555_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("WebsiteMonitor.Storage.Models.Instance", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("CheckIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConcurrencyLimit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("InstanceId");

                    b.ToTable("Instances", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
